language: python

python:
    - 3.7

cache: pip

install:
    - pip install coveralls
    - pip install python-dateutil
    - pip install mecab-python3

script:
    - coverage run --parallel-mode --rcfile=.coveragerc setup.py test
    - coverage run --parallel-mode --rcfile=.coveragerc example/momotaro.py --forcemecab

after_success:
    - coverage combine
    - coveralls
